name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    
jobs:
  run_test:
    name: CI - Testes da Aplicação
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Iniciando a execução dos Testes"
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: 17
         distribution: 'adopt'
      - name: Maven Verify  
        run: mvn clean verify
      - name: Test with Maven
        run: mvn -B test --file pom.xml

  run_build:
   name: CI - Build da aplicação
   runs-on: ubuntu-22.04
   needs: run_test
   steps:
    - run: echo "Iniciando a construção do Pacote da Aplicação"
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Maven Build
      run: mvn clean package -Dmaven.test.skip=true
    - name: Login to docker hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/hellocicd:${{ github.run_number }}
          ${{ secrets.DOCKERHUB_USERNAME }}/hellocicd:latest
  
  run_deploy:
    name: CD - Deploy no Railway 
    runs-on: ubuntu-22.04
    needs: run_build
    steps:
      - run: echo "Iniciando o Deploy da Aplicação"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x

      - name: Install Packages
        run: yarn install
        
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
